### ISSUE TITLE
.ejs over .nunjucks?

### ISSUE THREAD

**Issue by jan-dh** [ixartz/Eleventy-Starter-Boilerplate#4]
Was wondering if there was a specific reason for choosing .ejs of nunjucks? A lot of the eleventy plugins ( [Reading time](https://www.npmjs.com/package/eleventy-plugin-reading-time) for example) are only available for nunjucks.

**Comment by ixartz** [comment]
Hi @jan-dh, thank for your question. The main reason I use ejs is that you have access to javascript code in your template. Here is an example: https://github.com/ixartz/Eleventy-Starter-Boilerplate/blob/master/src/index.ejs#L23 or here, https://github.com/ixartz/Eleventy-Starter-Boilerplate/blob/master/src/index.ejs#L23

You can write you own JavaScript code.
