### ISSUE TITLE
Pre-sale question: do you maintain you templates?

### ISSUE THREAD

**Issue by pascalandy** [ixartz/Eleventy-Starter-Boilerplate#5]
I saw https://creativedesignsguru.com/category/eleventy/.

Really, what I'm looking in such a template is the developer experience. I saw this was updated 8 months ago. 
Does the premium templates are based on this project?

I want to find a great template to work along tailwindui.

Thanks!

**Comment by ixartz** [comment]
Hi @pascalandy,

Yes the premium templates are also based on this project.

Recently, I've just updated last week https://github.com/ixartz/Next-js-Blog-Boilerplate and I'll find the time next week to update this template.

The template can still be used, it's just the dependencies aren't in the latest version and the change is small.

I'll let you know when it's updated to the latest.

**Comment by pascalandy** [comment]
OK thanks!

**Comment by ixartz** [comment]
Hi @pascalandy,

I've just updated https://github.com/ixartz/Eleventy-Starter-Boilerplate and also update https://creativedesignsguru.com/category/eleventy/.

Now, it uses Eleventy 0.11, Webpack 5 and Tailwind CSS 2.

Let me know what do you think.

**Comment by pascalandy** [comment]
Thanks for taking the time to ping me :) I'll try it and let you know.

**Comment by pascalandy** [comment]
As this is a blog focused template, I won't need to use it. Thanks again!
