### ISSUE TITLE
how does post.ejs work? how to create additional template files like that?

### ISSUE THREAD

**Issue by ahillio** [ixartz/Eleventy-Starter-Boilerplate#7]
Sorry this question might not be specifically unique to this starter theme... I'm inexperienced with both 11ty and ejs and so I'm not sure which of those this question is most suited to.

How does `post.ejs` file get automatically used for pages in the `src/posts` directory?  Can you explain how I can do that for other pages?  Or could you point me to the part in the code where this is made?

**Comment by ahillio** [comment]
I see `src/posts/post.json` file which looks like part of how this works.  But if I do `cd src; mv posts post` that seems to break the blog.html page, so it looks like there's more to this than the `post.json` file???

**Comment by ahillio** [comment]
Is the line `permalink": "{{ page.fileSlug }}/index.html"` what controls the url for the pages in the /posts directory?  Is syntax an 11ty thing or an ejs thing?

**Comment by ixartz** [comment]
`page.fileSlug` is from 11ty: https://www.11ty.dev/docs/data-eleventy-supplied/#fileslug

To control `/posts` directory, it's an 11ty feature and it's named: https://www.11ty.dev/docs/data-cascade/

**Comment by ahillio** [comment]
Thank you for the links!!
