### ISSUE TITLE
How to add home and about page

### ISSUE THREAD

**Issue by thekamalkashyap** [ixartz/Eleventy-Starter-Boilerplate#8]
I was roaming around the web in the search of a simple yet attractive blogging site with netlify cms . this site is all i want . I configured it according to me and it looks awesome.but i am facing one issue i want to add a home and about page to my site. How can i do so ? Thank you in advance!

**Comment by ixartz** [comment]
Hi @thekamalkashyap, there is already a home page: https://github.com/ixartz/Eleventy-Starter-Boilerplate/blob/master/src/index.ejs

You can just add a new file inside this directory: https://github.com/ixartz/Eleventy-Starter-Boilerplate/tree/master/src
